/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSCalendar.h>


@interface NSCalendar (SBTimeUtilities)
-(BOOL)date:(id)date isSameYearAsDate:(id)date2;
-(BOOL)date:(id)date isSameDayAsDate:(id)date2;
-(id)_timeOnlyComponentsForDate:(id)date;
-(id)_dateOnlyComponentsForDate:(id)date;
@end

