/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDateComponents.h>


@interface NSDateComponents (SBTimeUtilities)
-(BOOL)isSameYearAsComponents:(id)components;
-(BOOL)isSameMonthAsComponents:(id)components;
-(BOOL)isSameDayAsComponents:(id)components;
@end

