/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSIndexPath.h>
#import "SpringBoard-Structs.h"


@interface NSIndexPath (SBIconIndex)
+(id)indexPathWithIconIndex:(unsigned)iconIndex listIndex:(unsigned)index;
+(id)emptyPath;
-(BOOL)isPrefixedByPath:(id)path;
-(id)indexPathWithPrefixPath:(id)prefixPath;
-(id)subpathFromPosition:(unsigned)position;
-(id)_subpathWithRange:(NSRange)range;
@end

