/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBAlertImageView : UIView {
	UIImageView* _imageView;
	UILabel* _labelView;
}
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame errorString:(id)string;
@end

