/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class SBAppContextHostManager;

__attribute__((visibility("hidden")))
@interface SBAppContextHostView : UIView {
	SBAppContextHostManager* _manager;
}
@property(assign, nonatomic) SBAppContextHostManager* manager;
-(id)window;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)description;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithDefaultSize;
@end

