/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIScrollView.h>

@protocol SBAppSwitcherScrollViewDelegate;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherScrollView : UIScrollView {
}
@property(assign, nonatomic) id<SBAppSwitcherScrollViewDelegate> delegate;
-(BOOL)touchesShouldCancelInContentView:(id)touches;
@end

