/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSOperation.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBApplicationUninstallationOperation : NSOperation {
	NSString* _bundleIdentifier;
}
-(void)main;
-(void)dealloc;
-(id)initWithBundleIdentifier:(id)bundleIdentifier;
@end

