/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UISlider.h>


__attribute__((visibility("hidden")))
@interface SBAppSwitcherSlider : UISlider {
}
-(UIEdgeInsets)_thumbHitEdgeInsets;
-(CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value;
-(CGRect)trackRectForBounds:(CGRect)bounds;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end

