/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSOperation.h>

@class NSSet;

__attribute__((visibility("hidden")))
@interface SBApplicationDataLookupOperation : NSOperation {
	NSSet* _registeredBundleIDs;
	NSSet* _unregisteredBundleIDs;
}
-(void)main;
-(void)dealloc;
-(id)initWithRegisteredBundleIDs:(id)registeredBundleIDs unregisteredBundleIDs:(id)ids;
@end

