/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface SBAppVisibilityPreferences : NSObject {
	BOOL _defaultVisible;
	BOOL _currentlyVisible;
}
@property(assign) BOOL currentlyVisible;
@property(readonly, assign) BOOL defaultVisible;
-(id)initWithDefaultVisible:(BOOL)defaultVisible;
@end

