/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherLabel : UIView {
	UILabel* _label;
}
@property(assign, nonatomic) BOOL marqueeRunning;
@property(copy, nonatomic) NSString* text;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

