/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UILabel.h>


__attribute__((visibility("hidden")))
@interface SBAppSwitcherUILabel : UILabel {
}
-(void)_drawFullMarqueeTextInRect:(CGRect)rect;
-(CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(int)lines;
@end

