/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import <SpringBoardUI/SBAlertItem.h>

@class SBApplicationIcon;

__attribute__((visibility("hidden")))
@interface SBAppProfileExpiredAlertItem : SBAlertItem <UIAlertViewDelegate> {
	SBApplicationIcon* _icon;
}
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithIcon:(id)icon;
@end

