/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImageView.h>


__attribute__((visibility("hidden")))
@interface SBAutoPurgingImageView : UIImageView {
	id _block;
}
-(void)setImage:(id)image;
-(void)didMoveToWindow;
-(void)dealloc;
-(id)initWithImageNamed:(id)imageNamed;
-(id)_initWithImageBlock:(id)imageBlock andInitialLoadBlock:(id)block;
@end

