/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UIButton, UIImageView;

__attribute__((visibility("hidden")))
@interface SBAwayBuddyBackgroundView : UIView {
	UIImageView* _titleView;
	UIButton* _infoButton;
}
-(void)setInfoButtonAlpha:(float)alpha;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

