/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBAwayListActionContext : NSObject {
	NSString* _lockLabel;
	NSString* _shortLockLabel;
	id _unlockAction;
	NSString* _bulletinID;
	float _fontsize;
	BOOL _requiresUnlock;
	BOOL _launchActionCanBypassPinLock;
	BOOL _hasCustomUnlockLabel;
	BOOL _canBypassPinLock;
}
@property(assign, nonatomic) BOOL hasCustomUnlockLabel;
@property(assign, nonatomic) BOOL requiresUnlock;
@property(assign, nonatomic) BOOL canBypassPinLock;
+(id)actionContextForCardItem:(id)cardItem;
+(id)actionContextForAlertItem:(id)alertItem;
+(id)actionContextForBulletin:(id)bulletin pluginActionsAllowed:(BOOL)allowed;
-(float)lockLabelFontSize;
-(id)bulletinID;
-(id)shortLockLabel;
-(id)lockLabel;
-(id)unlockAction;
-(void)dealloc;
-(id)_initWithLockLabel:(id)lockLabel shortLockLabel:(id)label unlockAction:(id)action bulletinID:(id)anId fontSize:(float)size;
-(id)_initWithLockLabel:(id)lockLabel shortLockLabel:(id)label unlockAction:(id)action bulletinID:(id)anId;
@end

