/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class SBSCardItem;

__attribute__((visibility("hidden")))
@interface SBAwayCardListItem : NSObject {
	SBSCardItem* _cardItem;
}
@property(copy, nonatomic) SBSCardItem* cardItem;
-(BOOL)inertWhenLocked;
-(id)sortDate;
-(void)dealloc;
@end

