/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBBatteryReflectionView : UIView {
	UIImage* _image;
	UIImage* _maskImage;
	float _bottomMargin;
}
-(void)drawRect:(CGRect)rect;
-(void)setImage:(id)image;
-(void)dealloc;
-(id)initWithImage:(id)image bottomMargin:(float)margin;
@end

