/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>

@class SUDescriptor;

__attribute__((visibility("hidden")))
@interface SBBaseSoftwareUpdateAlertItem : SBAlertItem {
	SUDescriptor* _descriptor;
}
@property(readonly, assign, nonatomic) SUDescriptor* descriptor;
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(BOOL)forcesModalAlertAppearance;
-(void)activateDisplayWithURL:(id)url;
-(void)activateSoftwareUpdateSettingsDisplay;
-(id)updateName;
-(void)dealloc;
-(id)initWithDescriptor:(id)descriptor;
@end

