/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface SBBrightnessController : NSObject {
	BOOL _debounce;
	BKSDisplayBrightnessTransactionRef _brightnessDownTransaction;
	BKSDisplayBrightnessTransactionRef _brightnessUpTransaction;
}
+(id)sharedBrightnessController;
-(void)cancelBrightnessEvent;
-(void)handleBrightnessEvent:(GSEventRef)event;
-(void)decreaseBrightnessAndRepeat;
-(void)increaseBrightnessAndRepeat;
-(void)setBrightnessLevel:(float)level;
-(void)_setBrightnessLevel:(float)level showHUD:(BOOL)hud;
-(void)adjustBacklightLevel:(BOOL)level;
-(float)_calcButtonRepeatDelay;
@end

