/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class SBBulletinLinenSegmentView, UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinLinenFadeView : UIView {
	SBBulletinLinenSegmentView* _fadeSegment;
	UIImageView* _fadeOverlayMask;
}
-(void)setGradientAlpha:(float)alpha;
-(void)setFrame:(CGRect)frame;
-(float)fadeHeight;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
@end

