/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"

@class BBObserver, NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBBulletinSoundController : NSObject <BBObserverDelegate, SBBulletinBusyClient> {
	BBObserver* _observer;
	NSMutableArray* _blockQueue;
	NSMutableDictionary* _playingSounds;
	BOOL _deviceIsLocked;
	BOOL _quietModeEnabled;
}
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
-(void)bulletinWindowStoppedBeingBusy;
-(void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)_enqueueBlock:(id)block;
-(BOOL)_shouldHonorPlaySoundRequestForBulletin:(id)bulletin;
-(void)_hardwareButtonPressed:(id)pressed;
-(void)_configureBBObserver;
-(void)killSounds;
-(void)killSoundForBulletin:(id)bulletin;
-(BOOL)playSoundForBulletin:(id)bulletin;
-(void)dealloc;
-(id)init;
@end

