/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBulletinAlertHandlerRegistry.h"
#import </libobjc.A.h>

@class NSMutableDictionary;

@protocol SBBulletinAlertHandlerRegistry
-(void)addAlertHandler:(id)handler forSection:(id)section;
@end

__attribute__((visibility("hidden")))
@interface SBBulletinAlertHandlerRegistry : NSObject <SBBulletinAlertHandlerRegistry> {
	NSMutableDictionary* _handlersBySectionID;
}
-(void)addAlertHandler:(id)handler forSection:(id)section;
-(id)alertHandlersForSection:(id)section;
-(void)dealloc;
-(id)init;
@end

