/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBulletinHeaderViewDelegate.h"
#import <UIKit/UITableView.h>
#import "SBBulletinFadeOverlayOwner.h"

@class NSMutableSet, SBBulletinLinenFadeView;

__attribute__((visibility("hidden")))
@interface SBBulletinTableView : UITableView <SBBulletinHeaderViewDelegate, SBBulletinFadeOverlayOwner> {
	NSMutableSet* _visibleSectionHeaders;
	SBBulletinLinenFadeView* _fadeContainer;
	BOOL _suppressUpdates;
	BOOL _hasReloadedOnce;
	unsigned _animatingUpdateCount;
}
@property(assign, nonatomic) BOOL suppressUpdates;
-(void)headerViewWillDisappear:(id)headerView;
-(void)headerViewWillAppear:(id)headerView;
-(BOOL)hasReloadedOnce;
-(void)reloadData;
-(void)endUpdates;
-(void)beginUpdates;
-(void)_decrementAnimatingCount;
-(void)_incrementAnimatingCount;
-(BOOL)isAnimatingUpdates;
-(void)layoutSubviews;
-(void)_orderHeierarchyAndAdjustLinenViewBackingAsNecessary;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)setRasterizesFadeOverlay:(BOOL)overlay;
-(id)visibleSectionHeaders;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame linenView:(id)view;
@end

