/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class BBSystemStateProvider, BBSettingsGateway;

__attribute__((visibility("hidden")))
@interface SBBulletinSystemStateAdapter : NSObject {
	BBSystemStateProvider* _stateProvider;
	BBSettingsGateway* _settingsGateway;
	BOOL _quietModeEnabled;
}
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
-(void)_lostModeStateChanged;
-(void)_screenDimmed:(id)dimmed;
-(void)_lockStateChanged:(id)changed;
-(BOOL)quietModeEnabled;
-(void)_activeBehaviorOverrideTypesChanged:(unsigned)changed;
-(void)dealloc;
-(id)init;
@end

