/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImageView.h>


__attribute__((visibility("hidden")))
@interface SBBulletinListTabView : UIImageView {
}
-(id)init;
@end

