/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UITableViewCell.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface SBBulletinLinenBackedCell : UITableViewCell {
	UIView* _linenView;
	BOOL _showsLinen;
}
@property(assign, nonatomic) BOOL showsLinen;
-(void)setFrame:(CGRect)frame;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)adjustLinenContents;
-(void)dealloc;
-(id)initWithLinenView:(id)linenView reuseIdentifier:(id)identifier;
@end

