/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBBulletinCellSelectionView : UIView {
	UIImageView* _gradientView;
	float _cellSeparatorHeight;
}
-(void)layoutSubviews;
-(void)setCellSeparatorHeight:(float)height;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

