/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


__attribute__((visibility("hidden")))
@interface SBCalendarApplicationIcon : SBApplicationIcon {
}
-(BOOL)canGenerateImageInBackgroundForFormat:(int)format;
-(id)generateIconImage:(int)image;
-(void)localeChanged;
-(void)dealloc;
-(id)initWithApplication:(id)application;
@end

