/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <SpringBoardUI/SBAlertItem.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBCallFailureAlertItem : SBAlertItem {
	long _causeCode;
	NSString* _address;
	CTCallRef _call;
}
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(id)shortLockLabel;
-(id)lockLabel;
-(void)_callback;
-(void)dealloc;
-(id)initWithCauseCode:(long)causeCode call:(CTCallRef)call;
@end

