/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface SBCalendarController : NSObject {
}
+(id)sharedInstance;
-(void)_significantTimeChange;
-(void)_checkForTimeZoneIfNecessary;
-(void)_finishInitialization;
-(void)dealloc;
-(id)init;
@end

