/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBCornerViewFactory : NSObject {
}
+(id)newCornerWindowForCorner:(int)corner windowLevel:(float)level cornersFrame:(CGRect)frame;
+(id)newCornerViewForCorner:(int)corner cornersFrame:(CGRect)frame;
@end

