/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class CALayerHost;

__attribute__((visibility("hidden")))
@interface SBContext : NSObject {
	unsigned _contextId;
	float _windowLevel;
	BOOL _hidden;
	BOOL _orderOutPending;
	CALayerHost* _layerHost;
}
@property(retain, nonatomic) CALayerHost* layerHost;
@property(assign, nonatomic, getter=isOrderOutPending) BOOL orderOutPending;
@property(assign, nonatomic, getter=isHidden) BOOL hidden;
@property(assign, nonatomic) float windowLevel;
@property(assign, nonatomic) unsigned contextId;
-(id)description;
-(void)dealloc;
@end

