/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBCompassRecalibrationController : NSObject {
	NSMutableArray* _assertionPorts;
}
+(id)sharedInstance;
-(void)_clientInvalidated:(CFMachPortRef)invalidated;
-(void)clientRequestedCompassHUD:(unsigned)hud;
-(void)removeHUD;
-(void)showHUD;
-(BOOL)isCompassCalibrationHUDVisible;
-(void)dealloc;
@end

