/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


__attribute__((visibility("hidden")))
@interface SBDaemonRequest : NSObject {
	id _enabler;
	id _disabler;
}
@property(copy, nonatomic) id disabler;
@property(copy, nonatomic) id enabler;
+(id)requestWithEnabler:(id)enabler disabler:(id)disabler;
-(void)dispatchDisablerOnQueue:(id)queue;
-(void)dispatchEnablerOnQueue:(id)queue;
-(void)dealloc;
@end

