/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBDataLookupResults : NSObject {
	NSDictionary* _applicationDictionaries;
	NSMutableSet* _registeredBundleIDs;
	NSMutableSet* _unregisteredBundleIDs;
}
@property(readonly, assign) NSMutableSet* unregisteredBundleIDs;
@property(readonly, assign) NSMutableSet* registeredBundleIDs;
@property(readonly, assign) NSDictionary* applicationDictionaries;
-(void)updateWithResults:(id)results;
-(void)dealloc;
-(id)initWithApplicationDictionaries:(id)applicationDictionaries registeredBundleIDs:(id)ids unregisteredBundleIDs:(id)ids3;
@end

