/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UILabel.h>
#import "SBBulletinDateLabel.h"

@class NSDate, NSTimer;
@protocol SBDateLabelDelegate;

__attribute__((visibility("hidden")))
@interface SBDefaultDateLabel : UILabel <SBBulletinDateLabel> {
	NSDate* _timeZoneRelativeStartDate;
	NSDate* _timeZoneRelativeEndDate;
	BOOL _allDay;
	NSDate* _effectiveAllDayStartDate;
	NSDate* _effectiveAllDayLastValidDate;
	NSDate* _effectiveAllDayEndDate;
	BOOL _effectiveAllDay;
	BOOL _isCoalescingUpdates;
	BOOL _needsUpdateFromCoalesce;
	NSTimer* _updateTimer;
	id<SBDateLabelDelegate> _delegate;
	int _labelType;
}
@property(assign, nonatomic) int labelType;
@property(assign, nonatomic) id<SBDateLabelDelegate> delegate;
@property(assign, nonatomic, getter=isAllDay) BOOL allDay;
+(id)_currentCalendar;
-(void)stopCoalescingUpdates;
-(void)startCoalescingUpdates;
-(void)update;
-(void)_forceUpdate;
-(void)updateTextIfNecessary;
-(void)_updateTimerFired:(id)fired;
-(void)updateTextIfNecessary:(BOOL)necessary;
-(id)constructLabelString;
-(BOOL)isEffectiveAllDay;
-(BOOL)isDateWithinEffectiveAllDayRange:(id)range;
-(id)_localDateForDate:(id)date inTimeZone:(id)timeZone;
-(void)_updateEffectiveAllDayTimes;
-(void)_resetEffectiveAllDayState:(BOOL)state;
-(void)setEndDate:(id)date withTimeZone:(id)timeZone;
-(void)setStartDate:(id)date withTimeZone:(id)timeZone;
-(void)setTimeZoneRelativeEndDate:(id)date;
-(void)setTimeZoneRelativeStartDate:(id)date absoluteStartDate:(id)date2;
-(void)_configureTimer;
-(void)_invalidateTimer;
-(void)prepareForReuse;
-(void)dealloc;
-(id)init;
@end

