/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDeviceLockDisableAssertion : NSObject {
	NSString* _identifier;
	int _type;
}
-(void)dealloc;
-(int)type;
-(id)description;
-(id)initWithIdentifier:(id)identifier type:(int)type;
@end

