/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconObserver.h"


@protocol SBDownloadingIconObserver <SBIconObserver>
@optional
-(void)downloadingIconStatusDidChange:(id)downloadingIconStatus;
@end

