/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBDownloadMetadataCache : NSObject {
	NSMutableSet* _fetchedDownloads;
}
+(id)sharedInstance;
-(void)downloadRemoved:(id)removed;
-(BOOL)artworkIsPrerenderedForDownload:(id)download;
-(id)applicationIdentifierForDownload:(id)download;
-(id)bundleIdentifierForDownload:(id)download;
-(id)titleForDownload:(id)download;
-(id)softwareTypeForDownload:(id)download;
-(void)_ensureMetadataCachedForDownload:(id)download;
-(id)init;
@end

