/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImageView.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface SBDownloadingProgressBar : UIImageView {
	UIView* _clipView;
	UIImageView* _fillView;
	float _progress;
}
+(float)defaultHeight;
-(void)updateFill;
-(float)progress;
-(void)setProgress:(float)progress;
-(id)fillImage;
-(id)trackImage;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

