/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface SBEmergencyCallView : UIView {
	UIView* _topBar;
}
-(void)dealloc;
-(void)setTopBar:(id)bar;
-(id)topBar;
-(id)initWithFrame:(CGRect)frame topBarFrame:(CGRect)frame2 bottomBarFrame:(CGRect)frame3;
@end

