/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIStatusBar.h>


__attribute__((visibility("hidden")))
@interface SBFakeStatusBarView : UIStatusBar {
	BOOL _initialized;
}
@property(assign, nonatomic) BOOL initialized;
+(id)allocWithZone:(NSZone*)zone;
-(oneway void)release;
-(id)retain;
-(void)dealloc;
-(void)_clearChanges;
-(id)initWithFrame:(CGRect)frame;
@end

