/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"

@class NSSet;

__attribute__((visibility("hidden")))
@interface SBFolderRotationAnimationContext : NSObject {
	NSSet* _icons;
	XXStruct_9ihRqB _notchInfo;
	double _duration;
}
@property(assign, nonatomic) double duration;
@property(assign, nonatomic) XXStruct_9ihRqB notchInfo;
@property(retain, nonatomic) NSSet* icons;
-(void)dealloc;
@end

