/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface SBFolderNotchHighlightView : UIView {
	XXStruct_9ihRqB _notchInfo;
}
-(void)drawRect:(CGRect)rect;
-(id)initWithNotchInfo:(XXStruct_9ihRqB)notchInfo;
@end

