/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UITextField.h>

@class UITextInteractionAssistant;

__attribute__((visibility("hidden")))
@interface SBFolderTextField : UITextField {
}
@property(readonly, assign, nonatomic) UITextInteractionAssistant* interactionAssistant;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(id)initWithFrame:(CGRect)frame;
@end

