/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBFolderScrollOffset : NSObject {
	CGPoint _scrollOffset;
	unsigned _identifier;
	int _orientation;
}
@property(assign) int orientation;
@property(assign) unsigned identifier;
@property(assign) CGPoint scrollOffset;
@end

