/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIImageView.h>

@class SBIconLabelImage;

__attribute__((visibility("hidden")))
@interface SBIconLabelImageView : UIImageView {
}
@property(retain, nonatomic) SBIconLabelImage* image;
-(id)description;
@end

