/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconObserver <NSObject>
@optional
-(void)iconLaunchEnabledDidChange:(id)iconLaunchEnabled;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)iconImageDidUpdate:(id)iconImage;
@end

