/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "SBBulletinFadeOverlayOwner.h"

@class SBBulletinLinenFadeView;

__attribute__((visibility("hidden")))
@interface SBLinenFadeContainer : UIView <SBBulletinFadeOverlayOwner> {
	UIView* _linenView;
	SBBulletinLinenFadeView* _fadeView;
}
-(void)setLinenGradientAlpha:(float)alpha;
-(void)setRasterizesFadeOverlay:(BOOL)overlay;
-(void)layoutSubviews;
-(void)setShouldShowFadeOverlay:(BOOL)showFadeOverlay;
-(void)dealloc;
-(id)initWithLinenView:(id)linenView;
-(id)initWithFrame:(CGRect)frame;
@end

