/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>


__attribute__((visibility("hidden")))
@interface SBLowPowerAlertItem : SBAlertItem {
	unsigned _talkLevel;
}
+(void)setBatteryLevel:(unsigned)level;
+(BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)batteryLevel;
+(unsigned)_thresholdForLevel:(unsigned)level;
+(void)initialize;
+(void)saveLowBatteryLogWithCapacity:(int)capacity voltage:(int)voltage;
+(id)systemVersionDescription;
-(BOOL)undimsScreen;
-(BOOL)shouldShowInEmergencyCall;
-(BOOL)shouldShowInLockScreen;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)willPresentAlertView:(id)view;
-(id)initWithLevel:(unsigned)level;
-(id)init;
@end

