/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>


__attribute__((visibility("hidden")))
@interface SBLockScreenAudioRoutesAlertItem : SBAlertItem {
}
-(void)audioRoutingPicker:(id)picker didSelectRouteAtIndex:(int)index;
-(void)performUnlockAction;
-(BOOL)allowAutoUnlock;
-(BOOL)togglesMediaControls;
-(BOOL)shouldShowInLockScreen;
-(void)willRelockForButtonPress:(BOOL)buttonPress;
-(BOOL)allowMenuButtonDismissal;
-(id)alertSheet;
-(Class)alertSheetClass;
@end

