/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITextField.h>


__attribute__((visibility("hidden")))
@interface SBManualKeyboardTextField : UITextField {
}
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
@end

