/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBMappedImageCache : NSObject {
	NSObject<OS_dispatch_queue>* _queue;
	NSString* _path;
	NSMutableDictionary* _images;
}
+(id)imageNamed:(id)named options:(int)options;
+(id)imageNamed:(id)named;
+(id)sessionCache;
+(id)persistentCache;
-(void)removeAllObjects;
-(void)removeImageForKey:(id)key;
-(void)warmupImageForKey:(id)key;
-(void)setImage:(id)image forKey:(id)key;
-(id)imageForKey:(id)key generateImageWithBlockIfNecessary:(id)blockIfNecessary;
-(id)imageForKey:(id)key options:(int)options generateImageWithBlockIfNecessary:(id)blockIfNecessary;
-(id)imageForKey:(id)key options:(int)options;
-(id)imageForKey:(id)key;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

