/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderIcon.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandIcon : SBFolderIcon {
}
+(Class)_iconGridImageClass;
+(unsigned)_maxIconsInGridImage;
-(BOOL)isNewsstandIcon;
-(id)folder;
-(void)launchFromViewSwitcher;
-(id)leafIdentifier;
-(id)displayName;
@end

