/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableView.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfTableView : UITableView {
	UIView* _backView;
}
@property(assign, nonatomic) UIView* shelfFrameView;
-(void)reloadData;
-(void)willRemoveSubview:(id)subview;
-(void)didAddSubview:(id)subview;
@end

