/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfView : UITableViewCell {
	UIImageView* _body;
	UIImageView* _leftEdge;
	UIImageView* _rightEdge;
	UIImageView* _shadowLeft;
	UIImageView* _shadowMiddle;
	UIImageView* _shadowRight;
	int _orientation;
	unsigned _shelfIndex;
	UILabel* _label;
}
+(id)shelf;
+(id)reuseIdentifier;
+(float)shelfItemBaselineOffset;
+(float)shelfEdgeHeight;
+(float)shelfHeight;
-(void)configureForOrientation:(int)orientation shelfIndex:(unsigned)index;
-(unsigned)shelfIndex;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

