/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBNewsstandTilingImageView : UIView {
	UIImage* _tileImage;
}
@property(retain, nonatomic) UIImage* _tileImage;
@property(retain, nonatomic) UIImage* image;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

