/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class SBNewsstandTilingImageView, SBNewsstandShelfHeaderView;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfFrameView : UIView {
	CGSize _borderSize;
	SBNewsstandShelfHeaderView* _headerView;
	SBNewsstandTilingImageView* _leftBorder;
	SBNewsstandTilingImageView* _rightBorder;
	int _orientation;
}
-(void)layoutSubviews;
-(void)configureForOrientation:(int)orientation;
-(void)setFrame:(CGRect)frame;
-(void)showHeaderView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

