/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface SBNoResultsView : UIView {
	UILabel* _noResultsLabel;
}
-(void)setShowsText:(BOOL)text;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

