/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBOrderedRequesters : NSObject {
	NSMutableArray* _bands[2];
}
-(id)description;
-(void)prioritizeRequester:(id)requester;
-(void)removeRequester:(id)requester;
-(void)addRequester:(id)requester toBand:(int)band;
-(BOOL)containsRequester:(id)requester inBand:(int)band;
-(id)requesters;
-(id)frontmostRequester;
-(void)dealloc;
-(id)init;
@end

