/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SBPhoneAlertItem : SBAlertItem {
	NSString* _bodyText;
	NSString* _title;
}
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithTitle:(id)title bodyText:(id)text;
@end

