/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface SBPluginManager : NSObject {
	NSString* _pluginsDirectory;
	NSMutableDictionary* _plugins;
}
+(id)sharedInstance;
-(Class)loadPluginBundle:(id)bundle;
-(Class)loadPluginNamed:(id)named;
-(void)loadAllLaunchPlugins;
-(id)springBoardPluginsDirectory;
-(void)dealloc;
-(id)init;
@end

