/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>


__attribute__((visibility("hidden")))
@interface SBRestoreFailureAlertItem : SBAlertItem {
	BOOL _runningModal;
}
-(BOOL)allowInSetup;
-(BOOL)forcesModalAlertAppearance;
-(BOOL)shouldShowInLockScreen;
-(BOOL)allowMenuButtonDismissal;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)restartSystemEvent;
-(void)_rebootNow;
-(double)autoDismissInterval;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)didPresentAlertView:(id)view;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

