/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSLock;

__attribute__((visibility("hidden")))
@interface SBResetManager : NSObject {
	BOOL _threadRunning;
	NSLock* _lock;
	int _mode;
	NSLock* _progressLock;
	float _progress;
}
+(id)sharedInstance;
-(void)_resetFinished;
-(void)_postResetEnded;
-(void)_resetThread;
-(void)_beginReset:(id)reset;
-(void)beginReset;
-(float)progress;
-(void)setProgress:(float)progress;
-(void)setMode:(int)mode;
-(void)dealloc;
-(id)init;
@end

