/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBAlertItem.h>

@class SBApplication;

__attribute__((visibility("hidden")))
@interface SBRemoteNotificationNeedIdentityAlert : SBAlertItem {
	SBApplication* _app;
}
-(BOOL)dismissOnModalDisplayActivation;
-(BOOL)dismissOnLock;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithApplication:(id)application;
@end

