/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBRemoteViewsController : NSObject {
	NSMutableDictionary* _registeredRemoteViewInfos;
	NSMutableDictionary* _unregisteredRemoteViewInfos;
}
+(id)sharedInstance;
-(void)unregisterRemoteViewsForApplication:(id)application;
-(id)proxyRemoteViewForIdentifier:(id)identifier;
-(void)_sequesterProxyRemoteView:(id)view;
-(id)_newProxyRemoteViewForIdentifier:(id)identifier;
-(void)unregisterRemoteIdentifier:(id)identifier application:(id)application;
-(void)registerRemoteContextID:(unsigned)anId forIdentifier:(id)identifier opaque:(BOOL)opaque size:(CGSize)size application:(id)application;
-(void)unregisterProxyRemoteView:(id)view;
-(void)dealloc;
-(id)init;
@end

