/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>

@class SBResetProgressView, NSTimer;

__attribute__((visibility("hidden")))
@interface SBResetView : UIView {
	SBResetProgressView* _progressView;
	NSTimer* _progressTimer;
}
-(void)_updateProgress;
-(void)_resetFinished:(id)finished;
-(void)_resetStarted:(id)started;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

