/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SBShowcaseViewControllerProtocol.h"

@class SBShowcaseController;

__attribute__((visibility("hidden")))
@interface SBShowcaseViewController : NSObject <SBShowcaseViewControllerProtocol> {
	SBShowcaseController* _showcase;
	int _revealMode;
}
@property(assign, nonatomic) int revealMode;
@property(assign, nonatomic) SBShowcaseController* showcase;
-(BOOL)activateIgnoringTouches;
-(BOOL)shouldShowLockStatusBarTime;
-(BOOL)expectsFaceContact;
-(void)revealModeWillChange:(int)revealMode;
-(float)revealAmountForMode:(int)mode;
-(float)bottomBarHeight;
-(void)viewDidRotateFromInterfaceOrientation:(int)view;
-(void)viewWillAnimateRotationToInterfaceOrientation:(int)view;
-(void)viewWillRotateToInterfaceOrientation:(int)view;
-(void)viewDidDisappear;
-(void)viewWillDisappear;
-(void)viewDidAppear;
-(void)viewWillAppear;
-(id)view;
@end

