/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBSIMLockEntryAlert : SBAlert {
	int _status;
}
-(void)deactivate;
-(void)activate;
-(int)status;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(id)init;
@end

