/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SpringBoard-Structs.h"

@class NSString, SBSIMLockAlertItem, SBSIMLockEntryAlert;

__attribute__((visibility("hidden")))
@interface SBSIMLockManager : NSObject {
	BOOL _isInitialUpdate;
	BOOL _isBrickedDevice;
	int _status;
	SBSIMLockAlertItem* _currentAlert;
	SBSIMLockEntryAlert* _lockEntryAlert;
	NSString* _languageCode;
	BOOL _hasHadSIMWhileNotBricked;
	BOOL _wasActivated;
	BOOL _neededUIM;
}
+(id)sharedInstance;
-(id)languageCode;
-(int)status;
-(void)registerForAlerts;
-(void)_postponementDidChange;
-(void)_telephonyDidRestart;
-(void)_activationDidChange;
-(void)_initialUpdate;
-(void)_externalSIMStatusChanged:(id)changed;
-(int)pukLockAttemptsRemaining;
-(int)pinLockAttemptsRemaining;
-(void)_updateSIMStatus:(CFStringRef)status withOptions:(CFDictionaryRef)options;
-(void)_tearDownAlertAndUpdateStatus;
-(void)_handlePromptForUnlock;
-(void)airplaneModeChanged;
-(void)_tryToUpdateStatus;
-(void)_updateToStatus:(int)status;
-(void)attemptUnlock;
-(void)repopAlert;
-(void)_setupAppActivationStateDidChange:(id)_setupAppActivationState;
-(BOOL)_shouldSuppressAlert;
-(void)alertItemDismissed:(id)dismissed;
-(void)lockEntryAlertDismissed:(id)dismissed;
-(int)_statusFromCT;
-(int)_CTToSBSIMStatus:(CFStringRef)sbsimstatus;
-(BOOL)_hopelesslyPUKLocked;
-(void)dealloc;
-(id)init;
@end

