/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUSSDAlert.h"


__attribute__((visibility("hidden")))
@interface SBSMSClass0Alert : SBUSSDAlert {
}
+(void)defaultAlertTonePrefChanged;
+(void)playMessageReceived;
+(BOOL)shouldPlayMessageReceived;
+(void)registerForAlerts;
-(void)deactivate;
-(id)_initWithString:(id)string;
-(void)_registerForNotifications;
-(void)_unregisterForNotifications;
@end

