/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSMutableDictionary, NSHashTable, SBUISound, AVController;

__attribute__((visibility("hidden")))
@interface SBSoundController : NSObject {
	NSMutableDictionary* _soundsBySystemSoundIDs;
	AVController* _ringtoneController;
	id _ringtoneObserver;
	SBUISound* _ringtoneSound;
	NSHashTable* _observers;
	unsigned _pendingCallbacks;
	NSMutableArray* _pendedCallbacks;
}
+(id)sharedInstance;
-(void)_enqueueCallback:(id)callback;
-(void)_endPendingCallbacksBlock;
-(void)_beginPendingCallbacksBlock;
-(void)_soundDidFinishPlaying:(id)_sound;
-(void)_soundDidStartPlaying:(id)_sound;
-(void)_ringerStateChanged:(id)changed;
-(BOOL)_playRingtone:(id)ringtone;
-(BOOL)_playSystemSound:(id)sound;
-(void)_killRingtone;
-(void)_cleanupSystemSound:(unsigned long)sound andKill:(BOOL)kill;
-(BOOL)handleVolumeButtonDownEvent;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)stopAllSounds;
-(BOOL)_stopAllSounds;
-(void)stopSound:(id)sound;
-(BOOL)playSound:(id)sound completion:(id)completion;
-(BOOL)playSound:(id)sound;
-(BOOL)isPlaying:(id)playing;
-(BOOL)isPlayingAnySound;
-(void)dealloc;
-(id)init;
@end

