/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIWindow.h>


__attribute__((visibility("hidden")))
@interface SBSpringBoardMetaHostingWindow : UIWindow {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)_isWindowServerHostingManaged;
@end

