/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>


__attribute__((visibility("hidden")))
@interface SBSystemLocalNotificationAlertSheet : UIAlertView {
	BOOL _lockToPortrait;
}
-(BOOL)requiresPortraitOrientation;
-(void)setLockToPortrait:(BOOL)portrait;
@end

