/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;
@protocol OS_dispatch_source, SBThermalWarningSuppressionAssertionDelegate;

__attribute__((visibility("hidden")))
@interface SBThermalWarningSuppressionAssertion : NSObject {
	id<SBThermalWarningSuppressionAssertionDelegate> _delegate;
	NSString* _reason;
	unsigned _clientPort;
	NSObject<OS_dispatch_source>* _source;
}
@property(readonly, assign, nonatomic) NSString* reason;
@property(assign, nonatomic) id<SBThermalWarningSuppressionAssertionDelegate> delegate;
-(id)description;
-(void)dealloc;
-(id)initWithClientPort:(unsigned)clientPort reason:(id)reason;
@end

