/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBTransientSettings : NSObject {
	NSMutableDictionary* _transientSettings;
	BOOL _dirty;
}
+(id)sharedInstance;
-(void)_load;
-(id)_path;
-(void)save;
-(void)reload;
-(id)objectForKey:(id)key;
-(void)setValue:(id)value forKey:(id)key;
-(void)dealloc;
-(id)init;
@end

