/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <SpringBoardUI/SBUISound.h>


@interface SBUISound (CompletionSupport)
-(void)_setCompletionBlock:(id)block;
-(id)_completionBlock;
@end

@interface SBUISound (SBUtilities)
-(id)initWithBBSound:(id)bbsound;
@end

