/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface SBUIRootView : UIView {
	BOOL _animatingAlpha;
}
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setAlpha:(float)alpha;
-(void)_actuallySetAlpha:(float)alpha;
-(id)initWithFrame:(CGRect)frame;
@end

