/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface SBUserNotificationAlertSheet : UIAlertView {
	UIImage* _alertImage;
}
@property(retain, nonatomic) UIImage* alertImage;
-(id)_maskedAlertImage;
-(void)dealloc;
-(void)layout;
-(void)dismissWithClickedButtonIndex:(int)clickedButtonIndex animated:(BOOL)animated;
@end

