/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIView.h>
#import "SBBulletinFadeOverlayOwner.h"

@class UIViewController, SBWeeApp;
@protocol BBWeeAppPresentationController;

__attribute__((visibility("hidden")))
@interface SBWeeAppPresentationView : UIView <SBBulletinFadeOverlayOwner> {
	BOOL _isDismissing;
	UIViewController<BBWeeAppPresentationController>* _viewController;
	SBWeeApp* _weeApp;
}
@property(retain, nonatomic) UIViewController<BBWeeAppPresentationController>* viewController;
@property(retain, nonatomic) SBWeeApp* weeApp;
-(void)setLinenGradientAlpha:(float)alpha;
-(void)setRasterizesFadeOverlay:(BOOL)overlay;
-(void)dismissWithCompletion:(id)completion;
-(void)willMoveToWindow:(id)window;
-(void)dealloc;
-(id)initWithWeeApp:(id)weeApp;
-(id)initWithFrame:(CGRect)frame;
@end

