/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface SBWorkspaceEvent : NSObject {
	NSString* _label;
	id _handler;
	NSArray* _callStackSymbols;
}
@property(copy, nonatomic) id handler;
@property(copy, nonatomic) NSArray* callStackSymbols;
@property(copy, nonatomic) NSString* label;
+(id)eventWithLabel:(id)label handler:(id)handler;
-(BOOL)isEqualToEvent:(id)event;
-(void)execute;
-(id)debugDescription;
-(id)description;
-(void)dealloc;
-(id)init;
@end

