/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class SBWorkspaceEventQueue;

__attribute__((visibility("hidden")))
@interface SBWorkspaceEventQueueLockAssertion : NSObject {
	SBWorkspaceEventQueue* _eventQueue;
}
-(void)dealloc;
-(id)initWithWorkspaceEventQueue:(id)workspaceEventQueue;
@end

