/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <UIKit/UIImage.h>


@interface UIImage (SBGraphics)
+(id)sbg_imageFromContextWithSize:(CGSize)size scale:(float)scale type:(int)type data:(id)data drawing:(id)drawing encapsulation:(id)encapsulation;
+(id)sbg_imageFromContextWithSize:(CGSize)size scale:(float)scale type:(int)type data:(id)data drawing:(id)drawing;
+(unsigned long)sbg_bytesNeededForSize:(CGSize)size scale:(float)scale withContextType:(int)contextType;
@end

