/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UILabel.h>
#import "SpringBoard-Structs.h"


@interface UILabel (SBStringDrawing)
-(void)drawWithMetrics:(id)metrics inContext:(CGContextRef)context;
-(id)stringMetricsForFirstLineWidth:(float)firstLineWidth;
@end

